In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from test import *

In [4]:
from datetime import date

In [5]:
today = date.today()
year = str(today.year)
month = str(today.month)
day = str(today.day)

In [6]:
if len(day) == 1:
    day = '0' + day
if len(month) == 1:
    month = '0' + month
iterDate = month + '/' + day + '/' + year
iterDate

'01/07/2022'

In [7]:
stocks = pd.read_excel('StockScraping.xlsx')

In [8]:
stocks.head(36)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31
0,NaN,NaN,STRIKE,NaN,NaN,Company,symbol,NaT,share price,One Yr. Pot,...,TTM Rev/Shr,NaN,Debt/Shr,Debt to Cap,NaN,TTM OP CF/Shr,TTM Lev Free CF/Shr,NaN,Dividend/shr,Div Yld
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,1.0,Continental Resources,CLR,2009-12-30,21.72,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,2.0,Continental Resources,CLR,2010-12-31,29.42,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,3.0,Continental Resources,CLR,2011-12-30,33.35,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,4.0,Continental Resources,CLR,2012-12-31,36.74,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,5.0,Continental Resources,CLR,2013-12-31,58.26,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,38.388592,NaN,NaN,6.0,Continental Resources,CLR,2014-12-31,38.36,NaN,...,11.5,NaN,16.245634,0.297508,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,22.983708,-104.471399,-287.296348,7.0,Continental Resources,CLR,2015-12-31,22.98,41,...,7.01,NaN,19.08796,0.453741,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,45.271020,-47.653706,NaN,8.0,Continental Resources,CLR,2016-06-30,45.27,46.15,...,5.78,NaN,19.303456,0.298938,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,51.541020,-57.911259,161.065689,9.0,Continental Resources,CLR,2016-12-30,51.54,59.61,...,5.54,NaN,17.75595,0.256234,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,45.423763,81.113863,37.232593,10.0,Continental Resources,CLR,2017-03-31,45.42,60.42,...,6.12,NaN,17.543387,0.278628,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,32.338824,85.102167,32.338824,11.0,Continental Resources,CLR,2017-06-30,32.33,54.21,...,6.38,NaN,17.678129,0.353505,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,38.611915,275.799392,68.949848,12.0,Continental Resources,CLR,2017-09-29,38.61,43.87,...,6.89,NaN,17.809511,0.315662,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,52.977660,151.364742,49.511831,13.0,Continental Resources,CLR,2017-12-29,52.97,51.73,...,7.6,NaN,17.108986,0.244139,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,14.0,Continental Resources,CLR,2018-03-29,58.95,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,15.0,Continental Resources,CLR,2018-06-29,64.76,73.25,...,10.09,NaN,16.590927,0.203943,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,16.0,Continental Resources,CLR,2018-09-28,68.28,75.72,...,11.48,NaN,16.022798,0.190062,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,17.0,Continental Resources,CLR,2018-12-31,40.19,67.99,...,11.78,NaN,15.510753,0.278466,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,18.0,Continental Resources,CLR,2019-03-27,43.74,NaN,...,11.74,NaN,15.518628,0.26188,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,19.0,Continental Resources,CLR,2019-06-28,42.09,58.95,...,11.72,NaN,15.341739,0.26713,NaN,NaN,NaN,NaN,0.2,0.004752
22,NaN,NaN,NaN,NaN,20.0,Continental Resources,CLR,2019-09-30,30.79,NaN,...,11.28,NaN,15.023424,0.327926,NaN,NaN,NaN,NaN,0.2,0.006496
23,NaN,NaN,NaN,NaN,21.0,Continental Resources,CLR,2019-12-31,34.3,NaN,...,11.4,NaN,14.372611,0.295292,NaN,NaN,NaN,NaN,0.2,0.005831
24,NaN,NaN,NaN,NaN,22.0,Continental Resources,CLR,2020-03-31,7.64,22.87,...,10.83,NaN,16.376831,0.68189,NaN,NaN,NaN,NaN,0,0
25,NaN,NaN,NaN,NaN,23.0,Continental Resources,CLR,2020-06-30,17.53,16.88,...,8.49,NaN,15.747816,0.473223,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,24.0,Continental Resources,CLR,2020-09-30,12.28,NaN,...,7.57,NaN,15.442324,0.557036,NaN,4.764121,-0.055445,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,25.0,Continental Resources,CLR,2020-12-31,16.3,17.27,...,6.66,NaN,15.170185,0.482049,NaN,3.888387,-0.000003,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,26.0,Continental Resources,CLR,2021-03-31,25.87,26.05,...,7.7,NaN,13.603961,0.344631,NaN,4.897426,1.569543,NaN,0.44,0.017008
29,NaN,NaN,NaN,NaN,27.0,Continental Resources,CLR,2021-06-30,38.03,34.68,...,10.55,NaN,12.950619,0.25403,NaN,6.774588,2.856754,NaN,0.6,0.015777
30,NaN,NaN,NaN,NaN,28.0,Continental Resources,CLR,2021-09-30,46.15,41.09,...,12.5,NaN,13.020406,0.220049,NaN,8.807922,3.911593,NaN,0.8,0.017335
31,NaN,NaN,NaN,NaN,29.0,Continental Resources,CLR,2021-11-19,45.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,30.0,Continental Resources,CLR,2022-03-31,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,31.0,Continental Resources,CLR,2022-06-30,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,32.0,Continental Resources,CLR,2022-09-30,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,33.0,Continental Resources,CLR,2022-12-31,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#stocks['orig'] = stocks.index

In [10]:
stocks.head(15)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31
0,NaN,NaN,STRIKE,NaN,NaN,Company,symbol,NaT,share price,One Yr. Pot,...,TTM Rev/Shr,NaN,Debt/Shr,Debt to Cap,NaN,TTM OP CF/Shr,TTM Lev Free CF/Shr,NaN,Dividend/shr,Div Yld
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,1.0,Continental Resources,CLR,2009-12-30,21.72,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,2.0,Continental Resources,CLR,2010-12-31,29.42,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,3.0,Continental Resources,CLR,2011-12-30,33.35,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,4.0,Continental Resources,CLR,2012-12-31,36.74,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,5.0,Continental Resources,CLR,2013-12-31,58.26,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,38.388592,NaN,NaN,6.0,Continental Resources,CLR,2014-12-31,38.36,NaN,...,11.5,NaN,16.245634,0.297508,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,22.983708,-104.471399,-287.296348,7.0,Continental Resources,CLR,2015-12-31,22.98,41,...,7.01,NaN,19.08796,0.453741,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,45.271020,-47.653706,NaN,8.0,Continental Resources,CLR,2016-06-30,45.27,46.15,...,5.78,NaN,19.303456,0.298938,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,51.541020,-57.911259,161.065689,9.0,Continental Resources,CLR,2016-12-30,51.54,59.61,...,5.54,NaN,17.75595,0.256234,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,45.423763,81.113863,37.232593,10.0,Continental Resources,CLR,2017-03-31,45.42,60.42,...,6.12,NaN,17.543387,0.278628,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,32.338824,85.102167,32.338824,11.0,Continental Resources,CLR,2017-06-30,32.33,54.21,...,6.38,NaN,17.678129,0.353505,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,38.611915,275.799392,68.949848,12.0,Continental Resources,CLR,2017-09-29,38.61,43.87,...,6.89,NaN,17.809511,0.315662,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
tickers = stocks['Unnamed: 6'].dropna().unique()

In [12]:
tickers

array(['symbol', 'CLR', 'KMI', 'MTDR', 'NOV', 'PTEN', 'RIG', 'RRC', 'SU'],
      dtype=object)

In [13]:
tickers = tickers[tickers != 'symbol']

In [14]:
tickers

array(['CLR', 'KMI', 'MTDR', 'NOV', 'PTEN', 'RIG', 'RRC', 'SU'],
      dtype=object)

In [15]:
checkStocks = stocks[stocks['Unnamed: 6'] == 'CLR']

In [16]:
checkStocks

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31
3,NaN,NaN,NaN,NaN,1.0,Continental Resources,CLR,2009-12-30,21.72,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,2.0,Continental Resources,CLR,2010-12-31,29.42,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,3.0,Continental Resources,CLR,2011-12-30,33.35,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,4.0,Continental Resources,CLR,2012-12-31,36.74,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,5.0,Continental Resources,CLR,2013-12-31,58.26,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,38.388592,NaN,NaN,6.0,Continental Resources,CLR,2014-12-31,38.36,NaN,...,11.5,NaN,16.245634,0.297508,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,22.983708,-104.471399,-287.296348,7.0,Continental Resources,CLR,2015-12-31,22.98,41,...,7.01,NaN,19.08796,0.453741,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,45.271020,-47.653706,NaN,8.0,Continental Resources,CLR,2016-06-30,45.27,46.15,...,5.78,NaN,19.303456,0.298938,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,51.541020,-57.911259,161.065689,9.0,Continental Resources,CLR,2016-12-30,51.54,59.61,...,5.54,NaN,17.75595,0.256234,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,45.423763,81.113863,37.232593,10.0,Continental Resources,CLR,2017-03-31,45.42,60.42,...,6.12,NaN,17.543387,0.278628,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,32.338824,85.102167,32.338824,11.0,Continental Resources,CLR,2017-06-30,32.33,54.21,...,6.38,NaN,17.678129,0.353505,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,38.611915,275.799392,68.949848,12.0,Continental Resources,CLR,2017-09-29,38.61,43.87,...,6.89,NaN,17.809511,0.315662,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,52.977660,151.364742,49.511831,13.0,Continental Resources,CLR,2017-12-29,52.97,51.73,...,7.6,NaN,17.108986,0.244139,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,14.0,Continental Resources,CLR,2018-03-29,58.95,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,15.0,Continental Resources,CLR,2018-06-29,64.76,73.25,...,10.09,NaN,16.590927,0.203943,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,16.0,Continental Resources,CLR,2018-09-28,68.28,75.72,...,11.48,NaN,16.022798,0.190062,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,17.0,Continental Resources,CLR,2018-12-31,40.19,67.99,...,11.78,NaN,15.510753,0.278466,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,18.0,Continental Resources,CLR,2019-03-27,43.74,NaN,...,11.74,NaN,15.518628,0.26188,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,19.0,Continental Resources,CLR,2019-06-28,42.09,58.95,...,11.72,NaN,15.341739,0.26713,NaN,NaN,NaN,NaN,0.2,0.004752
22,NaN,NaN,NaN,NaN,20.0,Continental Resources,CLR,2019-09-30,30.79,NaN,...,11.28,NaN,15.023424,0.327926,NaN,NaN,NaN,NaN,0.2,0.006496
23,NaN,NaN,NaN,NaN,21.0,Continental Resources,CLR,2019-12-31,34.3,NaN,...,11.4,NaN,14.372611,0.295292,NaN,NaN,NaN,NaN,0.2,0.005831
24,NaN,NaN,NaN,NaN,22.0,Continental Resources,CLR,2020-03-31,7.64,22.87,...,10.83,NaN,16.376831,0.68189,NaN,NaN,NaN,NaN,0,0
25,NaN,NaN,NaN,NaN,23.0,Continental Resources,CLR,2020-06-30,17.53,16.88,...,8.49,NaN,15.747816,0.473223,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,24.0,Continental Resources,CLR,2020-09-30,12.28,NaN,...,7.57,NaN,15.442324,0.557036,NaN,4.764121,-0.055445,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,25.0,Continental Resources,CLR,2020-12-31,16.3,17.27,...,6.66,NaN,15.170185,0.482049,NaN,3.888387,-0.000003,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,26.0,Continental Resources,CLR,2021-03-31,25.87,26.05,...,7.7,NaN,13.603961,0.344631,NaN,4.897426,1.569543,NaN,0.44,0.017008
29,NaN,NaN,NaN,NaN,27.0,Continental Resources,CLR,2021-06-30,38.03,34.68,...,10.55,NaN,12.950619,0.25403,NaN,6.774588,2.856754,NaN,0.6,0.015777
30,NaN,NaN,NaN,NaN,28.0,Continental Resources,CLR,2021-09-30,46.15,41.09,...,12.5,NaN,13.020406,0.220049,NaN,8.807922,3.911593,NaN,0.8,0.017335
31,NaN,NaN,NaN,NaN,29.0,Continental Resources,CLR,2021-11-19,45.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,30.0,Continental Resources,CLR,2022-03-31,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,31.0,Continental Resources,CLR,2022-06-30,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,32.0,Continental Resources,CLR,2022-09-30,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,33.0,Continental Resources,CLR,2022-12-31,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
latestDate = [0, 0, 0]
for idx in checkStocks.index:
    date = str(checkStocks['Unnamed: 15'][idx]).split(' ')
    if date[0] == 'nan':
        continue
    date = date[0].split('-')
    #print(date)
    if int(latestDate[0]) < int(date[0]):
        latestDate = date
        row = int(checkStocks['Unnamed: 4'][idx])
    elif int(latestDate[0]) == int(date[0]):
        if int(latestDate[1]) < int(date[1]):
            latestDate = date
            row = int(checkStocks['Unnamed: 4'][idx])
        elif int(latestDate[1]) == int(date[1]):
            if int(latestDate[2]) < int(date[2]):
                latestDate = date
                row = int(checkStocks['Unnamed: 4'][idx])
print(f'row: {row} date: {latestDate}')

row: 28 date: ['2021', '09', '30']

In [18]:
pulledData = pd.read_excel('gatheredData.xlsx')

In [19]:
pulledData

,Unnamed: 0,stockName,mostRecentQuarter,profitMargin,revenue,revenuePerShare,totalCashPerShare,totalDebt,currentRatio,bookValPerShare,operatingCashFlow,leveredCashFlow,sharesOutstanding,currentYearAvgEstimate,nextYearAvgEstimate
0,0,"Continental Resources, Inc. (CLR)",09/29/21,18.31%,4.51B,12.5,1.93,4.76B,1.41,19.05,3220000000,1.43B,365580000,4.5,6.16

In [20]:
pulledMostRecQ = pulledData['mostRecentQuarter']
p = pulledMostRecQ[0].split('/')

In [21]:
p

['09', '29', '21']

In [22]:
latestDate
latestYear = int(latestDate[0])
latestMonth = int(latestDate[1])
latestYear

2021

In [23]:
latestMonth

9

In [24]:
pulledMostRecQY = int(p[2]) + 2000
pulledMostRecQY

2021

In [25]:
pulledMostRecQM = int(p[0])
pulledMostRecQM

9

In [26]:
pulledMostRecQD = int(p[1])
pulledMostRecQD

29

In [37]:
if checkMostRecQ(pulled=pulledMostRecQY, curr=latestYear):
    row = int(row) + 1
    stocks.iloc(stocks[stocks['Unnamed: 4'] == row].index)
    pass
else:
    if checkMostRecQ(pulled=pulledMostRecQM, curr=latestMonth):
        row = int(row) + 1
        
        pass
    else:
        pass

In [33]:
stocks.head(40)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31
0,NaN,NaN,STRIKE,NaN,NaN,Company,symbol,NaT,share price,One Yr. Pot,...,TTM Rev/Shr,NaN,Debt/Shr,Debt to Cap,NaN,TTM OP CF/Shr,TTM Lev Free CF/Shr,NaN,Dividend/shr,Div Yld
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,1.0,Continental Resources,CLR,2009-12-30,21.72,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,2.0,Continental Resources,CLR,2010-12-31,29.42,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,3.0,Continental Resources,CLR,2011-12-30,33.35,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,4.0,Continental Resources,CLR,2012-12-31,36.74,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,5.0,Continental Resources,CLR,2013-12-31,58.26,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,38.388592,NaN,NaN,6.0,Continental Resources,CLR,2014-12-31,38.36,NaN,...,11.5,NaN,16.245634,0.297508,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,22.983708,-104.471399,-287.296348,7.0,Continental Resources,CLR,2015-12-31,22.98,41,...,7.01,NaN,19.08796,0.453741,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,45.271020,-47.653706,NaN,8.0,Continental Resources,CLR,2016-06-30,45.27,46.15,...,5.78,NaN,19.303456,0.298938,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,51.541020,-57.911259,161.065689,9.0,Continental Resources,CLR,2016-12-30,51.54,59.61,...,5.54,NaN,17.75595,0.256234,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,45.423763,81.113863,37.232593,10.0,Continental Resources,CLR,2017-03-31,45.42,60.42,...,6.12,NaN,17.543387,0.278628,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,32.338824,85.102167,32.338824,11.0,Continental Resources,CLR,2017-06-30,32.33,54.21,...,6.38,NaN,17.678129,0.353505,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,38.611915,275.799392,68.949848,12.0,Continental Resources,CLR,2017-09-29,38.61,43.87,...,6.89,NaN,17.809511,0.315662,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,52.977660,151.364742,49.511831,13.0,Continental Resources,CLR,2017-12-29,52.97,51.73,...,7.6,NaN,17.108986,0.244139,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,14.0,Continental Resources,CLR,2018-03-29,58.95,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,15.0,Continental Resources,CLR,2018-06-29,64.76,73.25,...,10.09,NaN,16.590927,0.203943,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,16.0,Continental Resources,CLR,2018-09-28,68.28,75.72,...,11.48,NaN,16.022798,0.190062,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,17.0,Continental Resources,CLR,2018-12-31,40.19,67.99,...,11.78,NaN,15.510753,0.278466,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,18.0,Continental Resources,CLR,2019-03-27,43.74,NaN,...,11.74,NaN,15.518628,0.26188,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,19.0,Continental Resources,CLR,2019-06-28,42.09,58.95,...,11.72,NaN,15.341739,0.26713,NaN,NaN,NaN,NaN,0.2,0.004752
22,NaN,NaN,NaN,NaN,20.0,Continental Resources,CLR,2019-09-30,30.79,NaN,...,11.28,NaN,15.023424,0.327926,NaN,NaN,NaN,NaN,0.2,0.006496
23,NaN,NaN,NaN,NaN,21.0,Continental Resources,CLR,2019-12-31,34.3,NaN,...,11.4,NaN,14.372611,0.295292,NaN,NaN,NaN,NaN,0.2,0.005831
24,NaN,NaN,NaN,NaN,22.0,Continental Resources,CLR,2020-03-31,7.64,22.87,...,10.83,NaN,16.376831,0.68189,NaN,NaN,NaN,NaN,0,0
25,NaN,NaN,NaN,NaN,23.0,Continental Resources,CLR,2020-06-30,17.53,16.88,...,8.49,NaN,15.747816,0.473223,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,24.0,Continental Resources,CLR,2020-09-30,12.28,NaN,...,7.57,NaN,15.442324,0.557036,NaN,4.764121,-0.055445,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,25.0,Continental Resources,CLR,2020-12-31,16.3,17.27,...,6.66,NaN,15.170185,0.482049,NaN,3.888387,-0.000003,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,26.0,Continental Resources,CLR,2021-03-31,25.87,26.05,...,7.7,NaN,13.603961,0.344631,NaN,4.897426,1.569543,NaN,0.44,0.017008
29,NaN,NaN,NaN,NaN,27.0,Continental Resources,CLR,2021-06-30,38.03,34.68,...,10.55,NaN,12.950619,0.25403,NaN,6.774588,2.856754,NaN,0.6,0.015777
30,NaN,NaN,NaN,NaN,28.0,Continental Resources,CLR,2021-09-30,46.15,41.09,...,12.5,NaN,13.020406,0.220049,NaN,8.807922,3.911593,NaN,0.8,0.017335
31,NaN,NaN,NaN,NaN,29.0,Continental Resources,CLR,2021-11-19,45.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,30.0,Continental Resources,CLR,2022-03-31,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,31.0,Continental Resources,CLR,2022-06-30,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,32.0,Continental Resources,CLR,2022-09-30,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,33.0,Continental Resources,CLR,2022-12-31,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,67.0,Kinder Morgan,KMI,2009-12-30,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,68.0,Kinder Morgan,KMI,2010-12-31,NAV,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,69.0,Kinder Morgan,KMI,2011-12-30,32.17,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,70.0,Kinder Morgan,KMI,2012-12-31,35.33,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
print(row)
stocks[stocks['Unnamed: 4'] == row].index

28

Int64Index([30], dtype='int64')

In [44]:
stocks

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31
0,NaN,NaN,STRIKE,NaN,NaN,Company,symbol,NaT,share price,One Yr. Pot,...,TTM Rev/Shr,NaN,Debt/Shr,Debt to Cap,NaN,TTM OP CF/Shr,TTM Lev Free CF/Shr,NaN,Dividend/shr,Div Yld
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,1.0,Continental Resources,CLR,2009-12-30,21.72,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,2.0,Continental Resources,CLR,2010-12-31,29.42,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,NaN,NaN,NaN,NaN,326.0,Suncor,SU,2021-11-19,25.03,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,NaN,NaN,NaN,NaN,327.0,Suncor,SU,2022-03-31,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,NaN,NaN,NaN,NaN,328.0,Suncor,SU,2022-06-30,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,NaN,NaN,NaN,NaN,329.0,Suncor,SU,2022-09-30,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,NaN,NaN,NaN,NaN,330.0,Suncor,SU,2022-12-31,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
stocks['Unnamed: 2'][3] = 'bye'

/var/folders/xt/5b4knh4j39l3kh5j0d6jhmdc0000gn/T/ipykernel_82624/2851361984.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stocks['Unnamed: 2'][3] = 'bye'

In [57]:
stocks.head

<bound method NDFrame.head of     Unnamed: 0  Unnamed: 1 Unnamed: 2  Unnamed: 3  Unnamed: 4  \
0          NaN         NaN     STRIKE         NaN         NaN
1          NaN         NaN        NaN         NaN         NaN
2          NaN         NaN        NaN         NaN         NaN
3          bye         NaN        NaN         NaN         1.0
4          NaN         NaN        NaN         NaN         2.0
..         ...         ...        ...         ...         ...
262        NaN         NaN        NaN         NaN       326.0
263        NaN         NaN        NaN         NaN       327.0
264        NaN         NaN        NaN         NaN       328.0
265        NaN         NaN        NaN         NaN       329.0
266        NaN         NaN        NaN         NaN       330.0

                Unnamed: 5 Unnamed: 6 Unnamed: 7   Unnamed: 8   Unnamed: 9  \
0                  Company     symbol        NaT  share price  One Yr. Pot
1                      NaN        NaN        NaT          NaN          NaN
2                      NaN        NaN        NaT          NaN          NaN
3    Continental Resources        CLR 2009-12-30        21.72          NaN
4    Continental Resources        CLR 2010-12-31        29.42          NaN
..                     ...        ...        ...          ...          ...
262                 Suncor         SU 2021-11-19        25.03          NaN
263                 Suncor         SU 2022-03-31          NaN          NaN
264                 Suncor         SU 2022-06-30          NaN          NaN
265                 Suncor         SU 2022-09-30          NaN          NaN
266                 Suncor         SU 2022-12-31          NaN          NaN

     ...  Unnamed: 22 Unnamed: 23 Unnamed: 24  Unnamed: 25  Unnamed: 26  \
0    ...  TTM Rev/Shr         NaN    Debt/Shr  Debt to Cap          NaN
1    ...          NaN         NaN         NaN          NaN          NaN
2    ...          NaN         NaN         NaN          NaN          NaN
3    ...          NaN         NaN         NaN          NaN          NaN
4    ...          NaN         NaN         NaN          NaN          NaN
..   ...          ...         ...         ...          ...          ...
262  ...          NaN         NaN         NaN          NaN          NaN
263  ...          NaN         NaN         NaN          NaN          NaN
264  ...          NaN         NaN         NaN          NaN          NaN
265  ...          NaN         NaN         NaN          NaN          NaN
266  ...          NaN         NaN         NaN          NaN          NaN

       Unnamed: 27          Unnamed: 28 Unnamed: 29   Unnamed: 30  Unnamed: 31
0    TTM OP CF/Shr  TTM Lev Free CF/Shr         NaN  Dividend/shr      Div Yld
1              NaN                  NaN         NaN           NaN          NaN
2              NaN                  NaN         NaN           NaN          NaN
3              NaN                  NaN         NaN           NaN          NaN
4              NaN                  NaN         NaN           NaN          NaN
..             ...                  ...         ...           ...          ...
262            NaN                  NaN         NaN           NaN          NaN
263            NaN                  NaN         NaN           NaN          NaN
264            NaN                  NaN         NaN           NaN          NaN
265            NaN                  NaN         NaN           NaN          NaN
266            NaN                  NaN         NaN           NaN          NaN

[267 rows x 32 columns]>

In [59]:
stocks.iloc[0]

Unnamed: 0                                                               NaN
Unnamed: 1                                                               NaN
Unnamed: 2                                                            STRIKE
Unnamed: 3                                                               NaN
Unnamed: 4                                                               NaN
Unnamed: 5                                                           Company
Unnamed: 6                                                            symbol
Unnamed: 7                                                               NaT
Unnamed: 8                                                       share price
Unnamed: 9                                                       One Yr. Pot
Unnamed: 10                                                              NaN
Earnings -----------------------------------------             Earnings - PY
Unnamed: 12                                               Earnings - CY Est.
Unnamed: 13                                           Earnings - Next Yr Est
Unnamed: 14                                                              NaN
Unnamed: 15                                                              mrq
Unnamed: 16                                                    Book Val/ Shr
Unnamed: 17                                                            $/Shr
Unnamed: 18                                                          C. Rat.
Unnamed: 19                                                              NaN
Unnamed: 20                                                     TTM Profit %
Unnamed: 21                                                     TTM Rev in B
Unnamed: 22                                                      TTM Rev/Shr
Unnamed: 23                                                              NaN
Unnamed: 24                                                         Debt/Shr
Unnamed: 25                                                      Debt to Cap
Unnamed: 26                                                              NaN
Unnamed: 27                                                    TTM OP CF/Shr
Unnamed: 28                                              TTM Lev Free CF/Shr
Unnamed: 29                                                              NaN
Unnamed: 30                                                     Dividend/shr
Unnamed: 31                                                          Div Yld
Name: 0, dtype: object

In [ ]:
{'stockName': [stockName],
 'mostRecentQuarter': [mostRecentQuarter],
 'profitMargin': [profitMargin], 
 'revenue': [revenue], 
 'revenuePerShare': [revenuePerShare], 
 'totalCashPerShare': [totalCashPerShare], 
 'totalDebt': [totalDebt], 
 'currentRatio': [currentRatio], 
 'bookValPerShare': [bookValPerShare], 
 'operatingCashFlow': [operatingCashFlow], 
 'leveredCashFlow': [leveredCashFlow], 
 'sharesOutstanding': [sharesOutstanding], 
 'currentYearAvgEstimate': [currentYearAvgEstimate], 
 'nextYearAvgEstimate': [nextYearAvgEstimate]}